guide_gym = {
    "chest supported row": {"tier": "s+"},
    "half kneeling 1 arm lat pulldown": {"tier": "s"},
    "meadows row": {"tier": "s"},
    "neutral grip cable row": {"tier": "s"},
    "neutral grip lat pulldown": {"tier": "s"},
    "wide grip lat pulldown": {"tier": "s"},
    
    "dumbbell preacher curl": {"tier": "s"},
    "dumbbell preacher hammer curl": {"tier": "s"},
    "face away bayesian cable curl": {"tier": "s+"},
    "machine preacher curl": {"tier": "s"},
    
    "machine chest press": {"tier": "s+"},
    "seated cable pec flye": {"tier": "s"},
    
    "behind the back cuffed lateral raise": {"tier": "s"},
    "cable lateral raise": {"tier": "s+"},
    "cable y raise": {"tier": "s"},
    "machine shoulder press": {"tier": "s"},
    "reverse cable crossover": {"tier": "s"},
    
    "dumbbell walking lunge": {"tier": "s+"},
    "machine hip abduction": {"tier": "s"},
    "nautilus glute drive": {"tier": "s"},
    "romanian deadlift": {"tier": "s"},
    
    "barbell back squat": {"tier": "s"},
    "bulgarian split squat": {"tier": "s"},
    "hack squat": {"tier": "s+"},
    "pendulum squat": {"tier": "s"},
    "smith machine squat": {"tier": "s"},
    
    "ez bar skullcrusher": {"tier": "s"},
    "overhead cable triceps extension (bar)": {"tier": "s+"}
}

quotes = [
    "The pain you feel today is the strength you gain tomorrow.",
    "Don’t count the reps. Make the reps count.",
    "Sweat is fat crying.",
    "You don’t have to be great to start, but you have to start to be great.",
    "The body achieves what the mind believes.",
    "Discipline is doing it when you don’t feel like it.",
    "Fall in love with the process.",
    "Train like a beast, look like a beauty.",
    "No excuses. Just results.",
    "Push yourself because no one else is going to do it for you.",
    "Slow progress is better than no progress.",
    "If it doesn’t challenge you, it doesn’t change you.",
    "You’re only one workout away from a better mood.",
    "Progress, not perfection.",
    "Work hard in silence, let success make the noise.",
    "Strive for progress, not excuses.",
    "One more rep, one step closer.",
    "Grind now, shine later.",
    "Strong body, strong mind.",
    "You vs You – win today.",
    "Rest later. Grind now.",
    "Your body can stand almost anything. It’s your mind you have to convince.",
    "Pain is temporary, pride is forever.",
    "Every rep is a step toward the dream.",
    "Earn it. Don’t expect it.",
    "Fit is not a destination. It’s a way of life.",
    "Be stronger than your excuses.",
    "You didn’t come this far to only come this far.",
    "Success starts with self-discipline.",
    "Your only limit is you.",
    "Wake up. Work out. Dominate.",
    "Excuses don’t burn calories.",
    "Hard work beats talent when talent doesn’t work hard.",
    "Sore today, strong tomorrow.",
    "Nothing will work unless you do.",
    "Results happen over time, not overnight.",
    "Crush the workout, conquer the day.",
    "You’re stronger than you think.",
    "Success is earned, not given.",
    "It’s not about having time. It’s about making time.",
    "Stay consistent. The results will come.",
    "Fitness is the reward for discipline.",
    "You don’t grow when you’re comfortable.",
    "One day or day one. You decide.",
    "Doubt kills more dreams than failure ever will.",
    "No pain, no gain – know pain, know gain.",
    "Start where you are. Use what you have. Do what you can.",
    "Fuel your grind with purpose.",
    "Winners are made in the reps no one sees.",
    "The hardest part is starting. The rest is progress."
]